### ISSUE TITLE
heroku?

### ISSUE THREAD

**Issue by Co1t0n** [moddedstuffguy/GeneralMathsMOD#1]
idk just wondering

**Comment by Co1t0n** [comment]
ah thanks! ill just pay most likely

**Comment by Co1t0n** [comment]
yeah only railway and heroku are actually unblocked and working at my school

**Comment by moddedstuffguy** [comment]
I see...
I am looking for support in railway.
My github account needs to be 90 days old to use railway

**Comment by moddedstuffguy** [comment]
@Co1t0n
If you can, please, deploy general maths mod to railway and share me the link so I put it as main link.
I am gonna put you as collaborator

**Comment by moddedstuffguy** [comment]
please, deploy also my Repo WomginxMOD
and also Nodeunblocker-heroku.
and put their links here

**Comment by Co1t0n** [comment]
ok but the railway site is blocked at my school ill deploy at home

**Comment by moddedstuffguy** [comment]
ok

**Comment by Co1t0n** [comment]
deploy failed

**Comment by moddedstuffguy** [comment]
Ok thanks. I see there is no support in railway...

**Comment by Co1t0n** [comment]
I could try render
