### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Harlan124** [moddedstuffguy/GeneralMathsMOD#17]
### Description of the bug

doesnt work 

### Steps To Reproduce

s

### Additional Information

s

**Comment by moddedstuffguy** [comment]
Please, specify what doesn't work

**Comment by Harlan124** [comment]
everything on the site the games, the proxys you did a bad job

**Comment by moddedstuffguy** [comment]
Proxies are working. Just try to click the game again

**Comment by moddedstuffguy** [comment]
Closed as doesn't follow Issue template and as completed
