### ISSUE TITLE
[BUG]: Type error failed to fetch

### ISSUE THREAD

**Issue by fnfgo** [moddedstuffguy/GeneralMathsMOD#6]
### Description of the bug

i cant do anything

### Steps To Reproduce

what

### Additional Information

HELP

**Comment by moddedstuffguy** [comment]
In which deploy platform? Replit or Render

**Comment by moddedstuffguy** [comment]
@fnfgo Send me a screenshot of the error

**Comment by moddedstuffguy** [comment]
Closed as similar issue already exist. We are currently working to fix Ultraviolet Proxy
